# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: cmreportingserviceapi   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_ROOT: '.' #Set the dotnet root
  DOTNET_VERSION: '7.0'                 # set this to the .NET Core version to use

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: LADevUser/PubApp-ChrisMarines-AzureArtefacts-POC
          path: '.'
          ref: 'master'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build PublicServiceReportAPI/PublicServiceReportAPI.sln --configuration 		Release

      - name: dotnet publish
        run: dotnet publish PublicServiceReportAPI/PublicServiceReportAPI.sln -c Release --property PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: /home/runner/work/PubApp-ChrisMarines-AzureArtefacts-POC/PubApp-ChrisMarines-AzureArtefacts-POC/PublicServiceReportAPI/PublicServiceReportAPI.WebApi/myapp/

